# Generated by Django 3.1.4 on 2021-05-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('programming_languages', models.CharField(choices=[('Python', 'JavaScript'), ('Java', 'PHP'), ('Ruby', 'C'), ('C++', 'Android'), ('Flutter', 'C#')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('qualification', models.CharField(max_length=255)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='social.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('freelancerCommenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='social.freelancer')),
            ],
        ),
    ]
